### ISSUE TITLE
Missing support for validating JWT token passed by iframe

### ISSUE THREAD

**Issue by korycins** [saleor/saleor-app-sdk#10]
Saleor app template has the function for verifying the JWT token(https://github.com/saleor/saleor-app-template/blob/main/lib/middlewares.ts#L37). 
This is something directly related to the communication App <-> Saleor. Maybe it would be worth having implementation for this in app-sdk.

@magul @zaiste What do you think?

**Comment by timuric** [comment]
@krzysztofwolski please take a look

**Comment by magul** [comment]
yes, it should and will be moved, just it wasn't high on our priority list

**Comment by korycins** [comment]
IMO the same thing is related to everything that is placed in https://github.com/saleor/saleor-app-template/tree/main/lib

**Comment by zaiste** [comment]
@korycins Yes, the plan is to move everything from `main/lib` to the SDK.
