### ISSUE TITLE
Improve Vercel APL docs

### ISSUE THREAD

**Issue by lkostrowski** [saleor/saleor-app-sdk#102]
https://github.com/saleor/saleor-app-sdk/blob/main/docs/apl.md#vercelapl

It was reported by @mmiszy that this docs can be confusing

We should make clear the difference between:
1. Hosting app in Vercel, using just env variables (add some EnvAPL read only?) 
2. Making clear that VercelAPL is made to be used with CLI and Marketplace

**Comment by krzysztofwolski** [comment]
Extracted task for the Env Variable APL to separate ticket: https://github.com/saleor/saleor-app-sdk/issues/140
Docs PR soon submitted
