### ISSUE TITLE
Create factory for handlers available only from the dashboard

### ISSUE THREAD

**Issue by krzysztofwolski** [saleor/saleor-app-sdk#104]
Applications usually have endpoints to fetch/update app configuration used by the App interface inside of the Dashboard.

The factory should return handler validating incoming requests and their tokens.

Ref #94
Ref https://github.com/saleor/react-storefront/pull/592

**Comment by lkostrowski** [comment]
@krzysztofwolski I'd start with some function that I can call from *any* handler like this

```
// handler body

await validateToken(req.token, apl.get(domain))
```

later we can build factory on top of that
