### ISSUE TITLE
Missing saleor-signature header produces TypeError

### ISSUE THREAD

**Issue by korycins** [saleor/saleor-app-sdk#13]
It is probably a small thing, but when an App receives a webhook request without a `saleor-signature` header, the `TypeError` is raised (and 500 is returned):
`error - TypeError: Cannot read properties of undefined (reading 'split')`
It happens when `withWebhookSignatureVerified` is used.

**Comment by magul** [comment]
Assuming that app developer put `withWebhookSignatureVerified` in his/her code, we should, in a situation that signature is not available, return `400 BAD REQUEST` here.
