### ISSUE TITLE
Use url safe base64 encoding in the Saleor Cloud APL 2.0

### ISSUE THREAD

**Issue by krzysztofwolski** [saleor/saleor-app-sdk#147]
The current implementation has a possibility of producing strings that will break generated URLs.
URL safe version replaces `/` with `_`, so it's not a breaking change for already existing AuthData

**Comment by lkostrowski** [comment]
Why not https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent

I think it was created for this case

![Zrzut ekranu 2023-01-17 o 09.03.39.png](https://images.zenhubusercontent.com/63563056fac74246940ede0c/44fec1e2-4fe0-4f0e-9e27-f02e0877b746)
