### ISSUE TITLE
Upstash APL write error

### ISSUE THREAD

**Issue by HazemKhaled** [saleor/saleor-app-sdk#198]
I'm struggling with Upstash recently, but I found the current approach is not working properly 

<img width="488" alt="image" src="https://user-images.githubusercontent.com/125433/221678548-8119ca77-eb3d-4a6c-9e31-93cdbf0c7610.png">

the current command
```["SET", "${authData.saleorApiUrl}", "${data}"]```

sent as 

```["SET", "https://hazem.eu.saleor.cloud/graphql/", "{"domain":"hazem.eu.saleor.cloud","token":"Ur74MzII5S8tJJ7FEAvSU9d0VLq5Sq","saleorApiUrl":"https://hazem.eu.saleor.cloud/graphql/","appId":"QXBwOjEwNQ==","jwks":" ..... "]```

Which needed to escape double quotes, especially in `jwks`

Solution:
Use RedisJSON, which is [supported recently](https://upstash.com/blog/redis-json) by Upstash

check this: https://docs.upstash.com/redis/sdks/javascriptsdk/modules/json#set

**Comment by lkostrowski** [comment]
@krzysztofwolski can you look into that? 

We can check RedisJSON or just escape JWKS (or encode)

**Comment by krzysztofwolski** [comment]
@HazemKhaled Issue has been fixed in the latest release of the App SDK. Thank you for reporting!
