### ISSUE TITLE
inferWebhooks should have a possibility to pass list of events

### ISSUE THREAD

**Issue by korycins** [saleor/saleor-app-sdk#26]
The current implementation of `inferWebhooks` ([src](https://github.com/saleor/saleor-app-sdk/blob/main/src/index.ts#L9)) assumes that event name will be taken from subscription filename. It is ok for basic usage but it would be usefull if we could explicitly provide a list of event names.
With this feature we will have a possibility to create single subscription to support multiple events. Like: I want to have single subscription for all order events.
Manifest:
```json
{
  ...
  "webhooks": [
    {
      "name": "Multiple order's events",
      "events": ["ORDER_CREATED", "ORDER_UPDATED", "ORDER_FULLY_PAID"],
      "query": "subscription { event { ... on OrderCreated { order { id }} ... on OrderFullyPaid { order { id }}}}",
      "targetUrl": "https://example.com/api/webhooks/order-event",
      "isActive": true
    }
  ]
}
```

**Comment by lkostrowski** [comment]
Hey @korycins FYI we will probably deprecated inferWebhooks from SDK and it will be an "example". Its too magical piece of code to be abstracted and it introduces confusion. In checkout, you can safely copy-pase src to your codebase
