### ISSUE TITLE
app-bridge scope and improvement ideas

### ISSUE THREAD

**Issue by Cloud11PL** [saleor/saleor-app-sdk#41]
This issue aims to aggregate ideas for app-bridge improvement based on its usage in apps.

In https://github.com/saleor/saleor-app-template/pull/38 it was suggested that:
- app-bridge should have a method for decoding the JWT token
- should export type ‘DashboardTokenPayload’
- (either app-bridge or sdk) check if token’s iss is valid and matches the domain passed

**Comment by lkostrowski** [comment]
@krzysztofwolski maybe we can implement this in some upcoming PRs
