### ISSUE TITLE
Add control of the browser history

### ISSUE THREAD

**Issue by mociepka** [saleor/saleor-app-sdk#63]
Right now, I can't control the main browser history. If I have a more extensive app with internal routing, users can't share links (the app contains only iframe history API).

Is there a plan to implement solutions like:
https://shopify.dev/apps/tools/app-bridge/getting-started/using-react#component

or for start an [action](https://github.com/saleor/saleor-app-sdk/blob/main/docs/app-bridge.md#available-actions)?

**Comment by lkostrowski** [comment]
@mociepka would you expect that browser URL changes and reflects dynamically URL from the app?

Like 
`my.saleor.cloud/dashboard/apps/XYZ/foo/bar/baz`, where `myapp.com/foo/bar/baz` is an internal routing?

**Comment by lkostrowski** [comment]
https://github.com/saleor/saleor-dashboard/pull/2551

**Comment by lkostrowski** [comment]
https://github.com/saleor/saleor-app-sdk/pull/110

**Comment by lkostrowski** [comment]
https://github.com/saleor/saleor-app-template/pull/122/
