### ISSUE TITLE
Replace `domain` parameter in APL with a full Saleor GraphQL API URL

### ISSUE THREAD

**Issue by mmiszy** [saleor/saleor-app-sdk#87]
Replace `domain` parameter in APL with a full Saleor GraphQL API URL. The new parameter could be named `saleorApiUrl`.

# Background
See: https://github.com/saleor/saleor-dashboard/issues/2387

**Comment by lkostrowski** [comment]
Rel https://github.com/saleor/saleor/issues/10819

**Comment by lkostrowski** [comment]
Done in https://github.com/saleor/saleor-dashboard/issues/2387

full url added, not replaced

**Comment by mmiszy** [comment]
This isn't done, APL still expects `domain` instead of full Saleor GraphQL API URL:
https://github.com/saleor/saleor-app-sdk/blob/b91bbf3d4e1b0f2cab5d27abc238aa85de53496f/src/APL/apl.ts#L2

**Comment by lkostrowski** [comment]
@mmiszy yes, its left for compatibility. APL interface requires a string, while CloudAPL accepts both URL and domain. You can construct domain/hostname from full URL, but of course name is wrong.

We also are working on next step, which is full migration of SDK and apps. APL will be extended to hold more fields (app ID, full URL) and domain will be deprecated.

I think you can safely use saleorApiUrl and put it to APL. We will soon orchestrate full migration

cc @krzysztofwolski @przlada

**Comment by lkostrowski** [comment]
@mmiszy this should be finally done in 0.26.0. We are currently updating apps, for example here 
https://github.com/saleor/saleor-app-invoices/pull/2

this introduces breaking changes (we used this change to improve architecture and add more fields to auth data)

we will update checkout when we finish with appstore apps
