### ISSUE TITLE
Can't open installed application on saleor dashboard

### ISSUE THREAD

**Issue by krzysztofzuraw** [saleor/saleor-app-sdk#93]
### How to reproduce
1. Login as tester account to staging environment 
2. Go `dashboard/apps/` and select app with id `QXBwOjI1Mg%3D%3D`

### Actual result
![CleanShot 2022-10-24 at 09 16 11@2x](https://user-images.githubusercontent.com/9116238/197468840-ef2d008d-6bf3-4f08-a0b6-7601d4081941.jpg)

### Expected result
I should be able to see configuration for this application

**Comment by lkostrowski** [comment]
@michalina-graczyk can you check?

**Comment by lkostrowski** [comment]
cLosing, probably stale
