### ISSUE TITLE
Create Webhook Handler factory

### ISSUE THREAD

**Issue by lkostrowski** [saleor/saleor-app-sdk#94]
`createSaleorWebhookHandler` exported from `@saleor/app-sdk/handler/next`

```
// src/pages/api/webhooks/order_created.ts

export default createSaleorWebhookHandler({
  eventType: string | string[] 
  ...
})

```

```
// eg:
const handler: SaleorEventHandler<OrderCreatedDocument | OrderFullfilledDocument> = (req, res) => {
  const {apl, payload, domain, eventType} = req.context;

  // logic
}

export default createSaleorWebhookHandler({
  handler: handler
})
```

- [x] Check what Saleor event type
- [x] Inject SaleorApp / APL instance
- [x] Validate tokens and headers
- [x] Check payload checksum
- [x] Type extending Next's request with Saleors metadata, eg `SaleorEventRequest<PayloadGraphqlDocument>`
- [ ] Allow multiple event types
- [x] Documentation
- [x] Example

**Comment by lkostrowski** [comment]
QA made on https://github.com/saleor/saleor-app-slack/pull/23

Here are problems:
1. Missing docs
2. When Webhook received empty query, installation failed, instead using some default payload
3. Wrong requests (eg empty body, wrong method) didn't receive error, error was somewhere silently handled

@krzysztofwolski

**Comment by krzysztofwolski** [comment]
1. Docs PR: #109
2. Added in #107
3. Added separate ticket
